# fly.toml app configuration file generated for casa-bonita-api

app = "casa-bonita-api"
primary_region = "mia"

[build]

[env]
  APP_ENV = "production"
  APP_DEBUG = "false"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  DB_CONNECTION = "pgsql"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/ping"

[machine]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1